import Head from "next/head";
import {
  Box
} from "@chakra-ui/react";
import WithSubnavigation from "../components/Navbar";
import CallToActionWithVideo from "../components/Hero";
import DataHydrationOnDemand from "../components/DataHydrationOnDemand";
import Footer from "../components/Footer";
import MeaningfulSection from "../components/MeaningfulSection";
import TestimonialsSection from "../components/TestimonialsSection";
import UserFriendlyContent from "../components/UserFriendlyContent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <Box maxW="100vw" overflow={"hidden"}>
        <WithSubnavigation />
       

        <CallToActionWithVideo />

        <UserFriendlyContent />
        <DataHydrationOnDemand />
        <TestimonialsSection />
        <MeaningfulSection />
        <Footer />
      </Box>
   
    </>
  );
}
